create table scheduled_posts (
  id bigint generated by default as identity primary key,
  text text not null,
  scheduled_at timestamp with time zone not null,
  status text not null check (status in ('pending', 'sent', 'failed')) default 'pending',
  tweet_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index scheduled_posts_status_idx on scheduled_posts (status);
create index scheduled_posts_scheduled_at_idx on scheduled_posts (scheduled_at);
